### PR TITLE
No-Jira: Add multiarch reviewers and approvers to OWNER file

### PR DESCRIPTION
**Pull request by Karthik-K-N**

### CODE REVIEW

**Comment by JoelSpeed** [comment]
I think you need to define an `OWNERS_ALIASES` file to be able to use groups like this

**Comment by Karthik-K-N** [comment]
> `OWNERS_ALIASES`

@JoelSpeed , @jaypoulz  may I know where Do I need to define this.

**Comment by mkumatag** [comment]
> > `OWNERS_ALIASES`
> 
> @JoelSpeed , @jaypoulz may I know where Do I need to define this.

something like this - https://github.com/openshift/release/blob/8745d27d5bde091ed1ff3521aa38d32c42b4599d/OWNERS_ALIASES#L339

**Comment by Karthik-K-N** [comment]
> > > `OWNERS_ALIASES`
> > 
> > 
> > @JoelSpeed , @jaypoulz may I know where Do I need to define this.
> 
> something like this - https://github.com/openshift/release/blob/8745d27d5bde091ed1ff3521aa38d32c42b4599d/OWNERS_ALIASES#L339

thanks, I thought it should be configured somewhere else also and used here.

**Pull request merged**
