### PR TITLE
No-Jira:  Manual rebase of upstream release 1.30 on 22-Jul-2024

### PR DESCRIPTION
**Pull request by Karthik-K-N**
Followed the procedure of https://github.com/openshift/cloud-provider-ibm/pull/41

Carried commits
```
UPSTREAM: <carry>: Add OWNERS
UPSTREAM: <carry>: Add vendor
UPSTREAM: <carry>: Added Support for PowerVS metadata service
UPSTREAM: <carry>: Add a Dockerfile that compatible with OpenShift
UPSTREAM: <carry>: snyk code scan exclude vendor directory
UPSTREAM: <carry>: Override service endpoints
UPSTREAM: <carry>: Updating ose-powervs-cloud-controller-manager-conainer image to be consistent with ART for 4.17
UPSTREAM: <drop>: Updating and vendoring go modules after an upstream rebase
```

Dropped commit as its already updated in upstream 
```
UPSTREAM: <carry>: fix govul with protobuf

```

### CODE REVIEW

**Comment by JoelSpeed** [comment]
What is the difference between this PR and https://github.com/openshift/cloud-provider-powervs/pull/71?

**Comment by Karthik-K-N** [comment]
In #71, its combination of release 1.29 and 1.30 it messed up as a part of updating the rebase bot configuration to 1.30 via [PR](https://github.com/openshift/release/pull/54392), 
I think its not correctly vendored and causing tests to fail.

I just manually rebased to 1.30 from now on wards expecting rebase bot to take care of  it.

**Comment by JoelSpeed** [comment]
/hold

Should we pre-merge verify this with QE?

**Comment by Karthik-K-N** [comment]
> /hold
> 
> Should we pre-merge verify this with QE?

I can quickly check and update it here.

**Comment by Karthik-K-N** [comment]
I have verified this on running against a cluster and could see both able to initialize a new node and create loadbalancer service.
```
% oc -n openshift-machine-api get machines.m
NAME                                PHASE     TYPE   REGION   ZONE      AGE
ocp-4171-fra02-6b4dx-master-0       Running   s922   eu-de    eu-de-2   10d
ocp-4171-fra02-6b4dx-master-1       Running   s922   eu-de    eu-de-2   10d
ocp-4171-fra02-6b4dx-master-2       Running   s922   eu-de    eu-de-2   10d
ocp-4171-fra02-6b4dx-worker-fgcfr   Running   s922   eu-de    eu-de-2   10d
ocp-4171-fra02-6b4dx-worker-n9t5x   Running   s922   eu-de    eu-de-2   17m
ocp-4171-fra02-6b4dx-worker-r2hdw   Running   s922   eu-de    eu-de-2   10d
ocp-4171-fra02-6b4dx-worker-xjrwg   Running   s922   eu-de    eu-de-2   10d


oc get svc
NAME         TYPE           CLUSTER-IP      EXTERNAL-IP                            PORT(S)        AGE
gg           LoadBalancer   172.30.138.46   7da00f99-eu-de.lb.appdomain.cloud      80:30663/TCP   8m50s
kubernetes   ClusterIP      172.30.0.1      <none>                                 443/TCP        10d
openshift    ExternalName   <none>          kubernetes.default.svc.cluster.local   <none>         10d

```

**Comment by Karthik-K-N** [comment]
@JoelSpeed Can this be merged?

**Pull request merged**
