### PR TITLE
MULTIARCH-5055: UPSTREAM: <carry>: Reuse authenticator in resource controller options

### PR DESCRIPTION
**Pull request by Karthik-K-N**
This PR has changes to reuse the authenticator for resource controller options, Authenticator can have iam endpoint override url.

### CODE REVIEW

**Comment by Karthik-K-N** [comment]
/hold

for testing

**Comment by Karthik-K-N** [comment]
This has been tested locally and works as expected.
/hold cancel

/cc @mkumatag  @mjturek

**Comment by mjturek** [comment]
@miyamotoh ran this locally as well and works like we expect, thanks for the patch!!

**Review by mkumatag — APPROVED** [review]
/lgtm

**Pull request merged**
