### PR TITLE
OCPBUGS-36105: UPSTREAM: <carry>: Fix go-retryablehttp CVE 4.14

### PR DESCRIPTION
**Pull request by Karthik-K-N**

### CODE REVIEW

**Review by mkumatag — APPROVED** [review]
/lgtm

**Comment by Karthik-K-N** [comment]
@multiarch-approvers someone please help with required labels.

**Comment by JoelSpeed** [comment]
@Karthik-K-N according to the [config](https://github.com/openshift/release/blob/81828834010a548fa5fe0b1c2f4dc65ed5247e04/core-services/prow/02_config/openshift/cloud-provider-powervs/_pluginconfig.yaml#L9-L16), you should be able to add the backport label yourself

**Comment by Karthik-K-N** [comment]
> @Karthik-K-N according to the [config](https://github.com/openshift/release/blob/81828834010a548fa5fe0b1c2f4dc65ed5247e04/core-services/prow/02_config/openshift/cloud-provider-powervs/_pluginconfig.yaml#L9-L16), you should be able to add the backport label yourself

I didn't knew that, Thank you.

**Comment by jaypoulz** [comment]
@Karthik-K-N A few months ago, I updated the configs for all of the Power VS repos so that team members could set their own labels. I omitted Joel on this one, but in my head he was included under the Staff Engineer's group. My bad!

**Comment by jaypoulz** [comment]
You still have "Invalid Bug" though. Please review the feedback from the bot above for how you need to update the bug.

**Review by djslavens — COMMENTED** [review]
/lgtm

**Pull request merged**
