### PR TITLE
OCPBUGS-12921: Updated net dependencies

### PR DESCRIPTION
**Pull request by jaypoulz**

### CODE REVIEW

**Comment by mkumatag** [comment]
It always good to update the dependency which is using that net package, I see this https://github.com/openshift/cloud-provider-powervs/pull/24 pending quite sometime to rebase the code with upstream repo. @Karthik-K-N can you check we stand and see if we can merge that one to take care of this CVE issue.?

**Comment by jaypoulz** [comment]
I have no qualms against moving on #24 first. If we decide on that direction, though, this PR will need to target 4.13 directly since #24 is not back portable for the 4.13 stream.

**Comment by jaypoulz** [comment]
It might be faster to land this and backport it into release-4.13 and then work on finishing #24.

@Karthik-K-N @mkumatag Let me know what you decide and I'll update the PRs accordingly.

**Comment by mkumatag** [comment]
> It might be faster to land this and backport it into release-4.13 and then work on finishing #24.
> 
> @Karthik-K-N @mkumatag Let me know what you decide and I'll update the PRs accordingly.

make sense, lets merge this for now on immediate action, will look at the rebase later when we have enough time,

**Review by mkumatag — APPROVED** [review]
/lgtm

**Pull request merged**
